CREATE TABLE IF NOT EXISTS `Item` (
	`itemId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`parentId`   INT(10) UNSIGNED NOT NULL DEFAULT 0,
	`name`       VARCHAR(50) NOT NULL,
	`position`   INT(10) UNSIGNED NOT NULL DEFAULT 0,

  PRIMARY KEY (`itemId`),
	INDEX `parentId` (`parentId`)
) ENGINE=InnoDB ROW_FORMAT=DEFAULT;

--//@UNDO
DROP TABLE `Item`;
